/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

/**
 *
 * @author carlos
 */
public class guiPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form guiPrincipal
     */
    public guiPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuSair = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPaciente = new javax.swing.JMenuItem();
        menuAgendar = new javax.swing.JMenuItem();
        menuProntuario = new javax.swing.JMenuItem();
        menuTriagem = new javax.swing.JMenuItem();
        menuMedico = new javax.swing.JMenuItem();
        menuEspecialidade = new javax.swing.JMenuItem();
        menuFuncionario = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prontuário Eletrônico");

        menuSair.setText("Arquivo");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuSair.add(jMenuItem1);

        jMenuBar1.add(menuSair);

        jMenu2.setText("Cadastro");

        menuPaciente.setText("Paciente");
        menuPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPacienteActionPerformed(evt);
            }
        });
        jMenu2.add(menuPaciente);

        menuAgendar.setText("Agendar");
        menuAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgendarActionPerformed(evt);
            }
        });
        jMenu2.add(menuAgendar);

        menuProntuario.setText("Prontuario");
        menuProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProntuarioActionPerformed(evt);
            }
        });
        jMenu2.add(menuProntuario);

        menuTriagem.setText("Triagem");
        menuTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTriagemActionPerformed(evt);
            }
        });
        jMenu2.add(menuTriagem);

        menuMedico.setText("Medico");
        menuMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMedicoActionPerformed(evt);
            }
        });
        jMenu2.add(menuMedico);

        menuEspecialidade.setText("Especialidade");
        menuEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEspecialidadeActionPerformed(evt);
            }
        });
        jMenu2.add(menuEspecialidade);

        menuFuncionario.setText("Funcionario");
        menuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(menuFuncionario);

        jMenuBar1.add(jMenu2);

        menuRelatorio.setText("Relatorio");

        jMenuItem2.setText("Relatorio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuRelatorio.add(jMenuItem2);

        jMenuBar1.add(menuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPacienteActionPerformed
        // TODO add your handling code here:
        new guiPaciente().setVisible(true);
    }//GEN-LAST:event_menuPacienteActionPerformed

    private void menuProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProntuarioActionPerformed
        // TODO add your handling code here:
        new guiProntuario().setVisible(true);
    }//GEN-LAST:event_menuProntuarioActionPerformed

    private void menuAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgendarActionPerformed
        // TODO add your handling code here:
        new guiAgenda().setVisible(true);
    }//GEN-LAST:event_menuAgendarActionPerformed

    private void menuTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTriagemActionPerformed
        // TODO add your handling code here:
        new guiTriagem().setVisible(true);
    }//GEN-LAST:event_menuTriagemActionPerformed

    private void menuMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMedicoActionPerformed
        // TODO add your handling code here:
        new guiMedico().setVisible(true);
    }//GEN-LAST:event_menuMedicoActionPerformed

    private void menuEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEspecialidadeActionPerformed
        // TODO add your handling code here:
        new guiEspecialidade().setVisible(true);
    }//GEN-LAST:event_menuEspecialidadeActionPerformed

    private void menuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionarioActionPerformed
        // TODO add your handling code here:
        new guiFuncionario().setVisible(true);
    }//GEN-LAST:event_menuFuncionarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new printRelatorio().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menuAgendar;
    private javax.swing.JMenuItem menuEspecialidade;
    private javax.swing.JMenuItem menuFuncionario;
    private javax.swing.JMenuItem menuMedico;
    private javax.swing.JMenuItem menuPaciente;
    private javax.swing.JMenuItem menuProntuario;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuTriagem;
    // End of variables declaration//GEN-END:variables
}
