/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

/**
 *
 * @author carlos
 */
import java.sql.*;
import javax.swing.*;
import static mondrian.rolap.sql.SqlQuery.newQuery;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.*;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;







public class printRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form printRelatorio
     */
    Connection conn = null;
    public printRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmdRelatorio.setText("Relatorio");
        cmdRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdRelatorioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(cmdRelatorio)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(cmdRelatorio)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdRelatorioMouseClicked
        // TODO add your handling code here:
        try{
            conn = Connect.ConnectionDB();
            //JasperDesign jasperDesign = JRXmlLoader.load("bdProntuario_Eletronico.jrxml");
             JasperDesign jasperDesign = JRXmlLoader.load("C:\\Users\\carlos\\bdProntuario_Eletronico.jrxml");
            String sql = "SELECT   PACI.NOME, TRIA.CA, TRIA.GLICEMIA, TRIA.PESO, FUNC.NOME\n" +
"  FROM   PACIENTE     PACI,\n" +
"         TRIAGEM      TRIA,\n" +
"         FUNCIONARIO  FUNC \n" +
" WHERE   PACI.ID  = TRIA.PACIENTE_ID          \n" +
"   AND   FUNC.ID  = TRIA.FUNCIONARIO_ID \n" +
"   AND   CAST(TRIA.PESO AS INT8) >= 70    \n" +
"   AND   CAST(TRIA.CA AS INT8) >= 3       \n" +
"   AND   PACI.NOME = 'Roberto'  ";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jasperDesign.setQuery(newQuery);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = jasperPrint= JasperFillManager.fillReport(jasperReport,null,conn);
            JasperViewer.viewReport(jasperPrint);
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
            
            
            
        }
        
    }//GEN-LAST:event_cmdRelatorioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdRelatorio;
    // End of variables declaration//GEN-END:variables
}
